### ISSUE TITLE
Tests fail: certificate has expired. Are there scripts for generating the certificates?

### ISSUE THREAD

**Issue by greenfork** [japhb/Cro-CBOR#1]
This is current test fail:

```
t/00-use.rakutest .................................................... ok
t/01-http-router-websocket.rakutest .................................. ok
t/02-websocket-client.rakutest .......................................1/14Tried to get the result of a broken Promise
  in block  at /home/grfork/rakudo/share/perl6/site/sources/EECBFFAFE1EB0CDBF5E9BEFF953D441C3690042E (Cro::TLS) line 110

Original exception:
    An operation first awaited:
      in block  at /home/grfork/rakudo/share/perl6/site/sources/8143677EA272A04F4BA3843A02BBD016F5269804 (IO::Socket::Async::SSL) line 405

    Died with the exception:
        Server certificate verification failed: certificate has expired
          in block  at /home/grfork/rakudo/share/perl6/site/sources/8143677EA272A04F4BA3843A02BBD016F5269804 (IO::Socket::Async::SSL) line 405

# You planned 14 tests, but ran 12
t/02-websocket-client.rakutest ....................................... Dubious, test returned 255
All 14 subtests passed
All tests successful.

Test Summary Report
-------------------
t/02-websocket-client.rakutest  (Wstat: 65280 Tests: 12 Failed: 0)
Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 14 tests but ran 12.
Files=3, Tests=21,  6 wallclock secs
Result: FAILED
```

I tried generating dummy certificates, I'm not sure what exactly they should contain, I got this error:

```
t/00-use.rakutest .................................................... ok
t/01-http-router-websocket.rakutest .................................. ok
t/02-websocket-client.rakutest .......................................1/14Tried to get the result of a bro
ken Promise
  in block  at /home/grfork/rakudo/share/perl6/site/sources/EECBFFAFE1EB0CDBF5E9BEFF953D441C3690042E (Cro:
:TLS) line 110

Original exception:
    An operation first awaited:
      in block  at /home/grfork/rakudo/share/perl6/site/sources/8143677EA272A04F4BA3843A02BBD016F5269804 (
IO::Socket::Async::SSL) line 405

    Died with the exception:
        Certificate contains no altnames to check host against
          in block  at /home/grfork/rakudo/share/perl6/site/sources/8143677EA272A04F4BA3843A02BBD016F52698
04 (IO::Socket::Async::SSL) line 405

# You planned 14 tests, but ran 12
t/02-websocket-client.rakutest ....................................... Dubious, test returned 255
All 14 subtests passed
All tests successful.

Test Summary Report
-------------------
t/02-websocket-client.rakutest  (Wstat: 65280 Tests: 12 Failed: 0)
Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 14 tests but ran 12.
Files=3, Tests=21,  6 wallclock secs
Result: FAILED
```

The error appears to be `Certificate contains no altnames to check host against`. Any idea how to solve the issue?

**Comment by japhb** [comment]
Yeah, test certificate expiry is a massive pain.  I went to check what Cro-TLS did, since that's the upstream for this, and it looks like jnthn just moved the certificate tests to `xt/` so they wouldn't run by default in https://github.com/croservices/cro-tls/commit/6a42be31ad88391e59fd4bf34837b62f875ee4f0 .

I can do the same here, but for now just skip the tests so you can keep going.  Meanwhile I'll look at rearranging the certificate tests.

**Comment by japhb** [comment]
Fixed in the repo via https://github.com/japhb/Cro-CBOR/commit/0ca16330597b4ba72e110712ea5b3dbe83659fd3 but I'm still working on getting `mi6 release` to allow the push with a broken `xt/` test.  :-/

**Comment by greenfork** [comment]
Here is a script I used to generate certificates, asked AI Mistral, these get failing "no altnames" as in the very first post, maybe it would be simpler to adapt them if mi6 won't allow to do that. I don't know what exactly needs to be modified for the error to be gone.

***

To generate SSL certificates for testing, you can use OpenSSL command line tool. Here are the steps to generate server public, server private, and client CA certificates:

1. Generate a private key for the server:
```bash
openssl genrsa -out server.key 4096
```
This will generate a 4096-bit RSA private key and save it to a file named `server.key`.
2. Generate a certificate signing request (CSR) for the server:
```bash
openssl req -new -key server.key -out server.csr
```
This will prompt you to enter information about the server, such as its common name (CN), organization, and country. The CSR will be saved to a file named `server.csr`.
3. Generate a self-signed certificate for the server:
```bash
openssl x509 -req -in server.csr -signkey server.key -out server.crt
```
This will generate a self-signed certificate using the CSR and the private key, and save it to a file named `server.crt`.
4. Generate a private key for the client CA:
```bash
openssl genrsa -out client-ca.key 4096
```
This will generate a 4096-bit RSA private key and save it to a file named `client-ca.key`.
5. Generate a self-signed certificate for the client CA:
```bash
openssl req -new -x509 -key client-ca.key -out client-ca.crt
```
This will prompt you to enter information about the client CA, such as its common name (CN), organization, and country. The self-signed certificate will be saved to a file named `client-ca.crt`.
6. Generate a private key for the client:
```bash
openssl genrsa -out client.key 4096
```
This will generate a 4096-bit RSA private key and save it to a file named `client.key`.
7. Generate a certificate signing request (CSR) for the client:
```bash
openssl req -new -key client.key -out client.csr
```
This will prompt you to enter information about the client, such as its common name (CN), organization, and country. The CSR will be saved to a file named `client.csr`.
8. Sign the client CSR with the client CA private key:
```bash
openssl x509 -req -in client.csr -CA client-ca.crt -CAkey client-ca.key -CAcreateserial -out client.crt
```
This will generate a client certificate signed by the client CA, and save it to a file named `client.crt`.

Now you have generated SSL certificates for testing: `server.key` and `server.crt` for the server, and `client.key` and `client.crt` for the client. The client CA certificate `client-ca.crt` can be used to verify the client certificate.

**Comment by japhb** [comment]
OK, I pulled over the TLS cert rebuilder script from cro-tls and refreshed the local certs.  This allowed a clean test run and a fresh release on fez.  Closing this issue.  :-)
